### ISSUE TITLE
Windows binary detected as trojan

### ISSUE THREAD

**Issue by jessica-gabi** [cucumber/json-formatter#23] opened 2022-07-24 14:44 UTC
### 👓 What did you see?

Windows binary detected as trojan:

https://www.virustotal.com/gui/file/a1b27a9647c6fffc2b0476ff2a52f147b7466c6f8df51fb995654412c776927a

### ✅ What did you expect to see?

Clean binary files

### 📦 Which tool/library version are you using?

https://github.com/cucumber/json-formatter/releases/tag/v19.0.0

### 🔬 How could we reproduce it?

Download windows binary https://github.com/cucumber/json-formatter/releases/download/v19.0.0/cucumber-json-formatter-windows-amd64

na dthen upload it to: https://www.virustotal.com/

### 📚 Any additional context?

The executable is trying to contact some weird ip addresses, one IP seems to be related to some sort of pishing websites:

![image](https://user-images.githubusercontent.com/83611918/180653707-e0a8c7ad-2551-493e-8aab-4957970d207f.png)

**Comment by veke** [comment] 2022-08-19 10:04
Any news on this?

**Comment by mpkorstanje** [comment] 2022-08-19 14:23
Duplicate of https://github.com/cucumber/json-formatter/issues/20, https://github.com/cucumber/common/issues/1681, https://github.com/cucumber/common/issues/1556,  https://github.com/cucumber/common/issues/1974. TL;DR: It's a go executable. See https://go.dev/doc/faq#virus

**Closed by mpkorstanje** 2022-08-19 14:23 UTC

**Comment by tobmaster** [comment] 2022-08-30 21:35
It seems like the issue is not that it's a go executable but that its additionally with reduced with UPX. At lest my current understanding. And I wonder if it's necessary.

**Comment by mpkorstanje** [comment] 2022-11-02 19:33
@tobmaster could you please create a new issue to elaborate on this in more detail? 

Nobody looks at closed issues. :sweat_smile:
