### ISSUE TITLE
not able to use cucumber-json-formatter-windows-amd64

### ISSUE THREAD

**Issue by navadeep1251** [cucumber/json-formatter#31] opened 2022-11-02 16:52 UTC
I am trying to convert the ndjson to json acceptable by XRAY to do that I have followed the documentation you have provided. But for some reason cucumber-json-formatter-windows-amd64 is flagging as malicious and our company is not allowing us to use that .exe. 
is there any workaround to use the formatter to convert into JSON.

**Comment by mpkorstanje** [comment] 2022-11-02 19:26
Duplicate of https://github.com/cucumber/json-formatter/issues/27 https://github.com/cucumber/json-formatter/issues/23, https://github.com/cucumber/json-formatter/issues/20, https://github.com/cucumber/common/issues/1681, https://github.com/cucumber/common/issues/1556,  https://github.com/cucumber/common/issues/1974. TL;DR: It's a go executable. See https://go.dev/doc/faq#virus

>  is there any workaround to use the formatter to convert into JSON.

You can build it yourself from source.

**Closed** 2022-11-02 19:27 UTC
